import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Theme, ThemePanel } from '@radix-ui/themes'
import { ClerkProvider } from '@clerk/nextjs'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className} style={{padding: 0, margin: 0}}>
          <Providers>
            <Theme accentColor="jade" radius="large">
              {children}
              {process.env.NODE_ENV == 'development' && <ThemePanel />}
            </Theme>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
